---
title: First words
author: oliver Belmans
date: '2015-11-11'
slug: first-words
categories:
  - General
tags: []
banner: 'banners/rocket.jpg'
description: ''
images: []
menu: ''
---

<!--more-->

From now this will be an experimental environment to write things about my field of interest, mostly related to data science.

As this will be the kick-off it must be clear what my starting-point is. I know a little of R compared to our R-master [Hadley Wickham](http://hadley.nz/) but do well on average. Not long ago – it must be two years – i started playing on [code academy](https://www.codecademy.com/) with a basic Java course just for fun. And soon, by the influence of a few friends/colleagues, i started playing with R. Just basic stuff like replacing a few excel tasks in R. Since then it try to learn everyday more and more about the field of data analytics. My most used R-packages are ofcourse dplyr, tidyr and ggplot2. Got the hang of making dashboards and apps with shiny and shinydashboard. And with [Rstudio](https://www.rstudio.com/) as a powerful IDE it has become really intuitive and fun to explore insights based on data. So basically I know a few good tools and language’s to full-fill the data-scientist-job, but I’m at the breach to explore a lot more. Also, I look forward to finish my ‘Master of Information Management’ at the University of Leuven. Which definitely will produce a lot more insights on machine learning concepts, data mining, simulations theory and a handful of tools/programming languages.

So lets explore more about advanced analytics one project at a time.

